# Extract allowed qualifiers for descriptors
# https://github.com/related-sciences/nxontology-data/issues/3
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
SELECT
  ?descriptor_id ?qualifier_id ?descriptor_label ?qualifier_label
WHERE {
  ?descriptor_uri meshv:allowableQualifier ?qualifier_uri.
  ?descriptor_uri meshv:identifier ?descriptor_id.
  ?qualifier_uri meshv:identifier ?qualifier_id.
  ?descriptor_uri rdfs:label ?descriptor_label.
  ?qualifier_uri rdfs:label ?qualifier_label.
}
ORDER BY ?descriptor_id ?qualifier_id
